### ISSUE TITLE
Potential bug in get_sum_cardinality

### ISSUE THREAD

**Issue by objarni** [primaryodors/podock#28]
This algorithm:

```
int Atom::get_sum_cardinality()
{
    if (!bonded_to) return 0;
    int i, retval=0;
    for (i=0; i<geometry; i++) if (bonded_to[i].btom) retval += bonded_to[i].cardinality;
    return retval;
}
```

.. returns an integer. However, cardinality is a float, and by its declaration says can be "1.5". This means retval will get +1 (implicit rounding to int --> becomes 1).

Is this intentional?

**Comment by ssepeq** [comment]
It's intentional, but I should probably enforce the rounding in code.

Cardinality usually has an integer value, e.g. single bonds, double, triple. Normally the variable itself would be declared as an int, except I've reluctantly decided on float to handle weird resonance cases where bonds are simultaneously single and double, as in benzene or carboxylates or nitrates. (This also allows bonds to be less than one, such as in hydrogen bonding.)

get_sum_cardinality() was intended to be used to determine how many bonds an atom already has, in order to know if it has room for more. Apparently, though, it's not being used anywhere.

**Comment by objarni** [comment]
I see! If it not being used, I'd just delete it (as a software engineer). It brings more confusion than value. You can always go back in version history if you're in that mood :)

**Comment by ssepeq** [comment]
This is true!
